server:
  port: ${PORT:9300}

spring:
  application:
    name: matlab-client

envoy:
  discovery:
    url: ${DISCOVERY_URL:http://192.168.31.177:9200}

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.31.177:8761/eureka/
  instance:
    prefer-ip-address: true